import pygame as pg

TILE_WIDTH = 32
TILE_HEIGHT = 32
SIZE_X_WORLD = 44
SIZE_Y_WORLD = 22
SCREENRECT = pg.Rect(0, 0, TILE_WIDTH * SIZE_X_WORLD, TILE_HEIGHT * SIZE_Y_WORLD)
TILES_PATH = "resources/sprites/tiles"

PLAYER_WIDTH = 128
PLAYER_HEIGHT = 128
