import pygame as pg

LARGEUR_TUILE = 32
HAUTEUR_TUILE = 32

LARGEUR_TERRAIN = 44
HAUTEUR_TERRAIN = 22

RESOLUTION = pg.Rect(
    0, 0,
    LARGEUR_TUILE * LARGEUR_TERRAIN, HAUTEUR_TUILE * HAUTEUR_TERRAIN
)

ACCES_TUILES = "themes/{}/tuiles"
ACCES_TERRAINS = "themes/{}/terrains"
ACCES_JOUEUR = "themes/{}/joueur"

LARGEUR_JOUEUR = 64
HAUTEUR_JOUEUR = 64
